version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: my_postgres
    restart: always
    env_file:
      - setup.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: node:20-alpine
    container_name: user_api
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - setup.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
